apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: rs
spec:
  # minReadySeconds: 30
  selector:
    matchLabels:
      app: rs
  replicas: 1
  template:
    metadata:
      labels:
        app: rs
    spec:
      containers:
        - name: rs
          image: richardchesterwood/k8s-fleetman-webapp-angular:release0-5
---
apiVersion: v1
kind: Service
metadata:
  name: rs
spec:
  selector:
    app: rs
  ports:
    - name: http
      port: 80
      nodePort: 30080
  type: NodePort