apiVersion: v1
kind: Pod
metadata:
  name: helloworld.example.com
  labels:
    app: helloworld
spec:
  containers:
  - name: kubernetes-demo
    image: daniarwido/kubernetes-demo
    ports:
    - containerPort: 3000
